min_version = 0.75
baseURL = "https://krossboard.app/"
languageCode = "en-us"
title = "Krossboard"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[params]
  author = "2Alchimists SAS"
  title = "Centralized Cross-cloud Kubernetes Usage Accounting"
  subtitle = "All in one single place, Krossboard tracks the usage of all your clusters over time. It simplifies usage accounting for cost allocation, helps forecast capacity scale up/down, thereby enabling to anticipate and master operations costs."
  description = "Kubernetes Usage Analytics for Cost and Capacity Management"
  releaseYear = "2020"
  github = "https://github.com/2-alchemists/krossboard"
  twitter = "https://twitter.com/krossboard"
  email = "contact@krossboard.app"
  logo = "/images/logo/krossboard-logo.png"
  favicon = "/images/favicon.ico"
  contactRequestApiEndpoint = "https://krossboard-mx.ey.r.appspot.com/sendmail"
  reCaptchaSiteKey = "HOSTING_RE_CAPTCHA_SITE_KEY"
  googleAnalytics = "HOSTING_FTP_PASSWORD"

