min_version = 0.73
baseURL = "https://krossboard.app/"
languageCode = "en-us"
title = "Krossboard"
googleAnalytics = "UA-158612003-1"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  author = "2Alchimists SAS"
  title = "Converged Kubernetes usage analytics"
  subtitle = "All in one single place, Krossboard tracks the usage of all your clusters over time, it helps forecast capacity scale up/down, thereby enabling you to easily anticipate and master operations costs."
  description = "Kubernetes Usage Analytics for Cost and Capacity Management"
  releaseYear = "2020"
  github = "https://github.com/2-alchemists/krossboard"
  twitter = "https://twitter.com/krossboard"
  email = "contact@krossboard.app"
  logo = "/images/logo/krossboard-logo.png"
  favicon = "/images/favicon.ico"
  contactRequestApiEndpoint = "https://krossboard-mx.ey.r.appspot.com/sendmail"
  reCaptchaSiteKey = "6Lc8J8AZAAAAAL0sB7htNmIyc9lxUZd6yJOhsihA"

