name: build site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
 
      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2.4.10
        with:
          hugo-version: '0.74.2'

      - name: build
        run: hugo --minify
