name: build site

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.75.1"
          # extended: true

      - name: build
        env:
          HOSTING_RE_CAPTCHA_SITE_KEY: ${{ secrets.HOSTING_RE_CAPTCHA_SITE_KEY }}
          HOSTING_ANALYTICS_ID: ${{ secrets.HOSTING_ANALYTICS_ID }}
        run: |
          sed -i 's/HOSTING_RE_CAPTCHA_SITE_KEY/'$HOSTING_RE_CAPTCHA_SITE_KEY'/' config.toml
          sed -i 's/HOSTING_RE_CAPTCHA_SITE_KEY/'$HOSTING_RE_CAPTCHA_SITE_KEY'/' config.toml
          hugo --minify
