name: deploy site

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.75.1"
          # extended: true

      - name: build
        env:
          HOSTING_RE_CAPTCHA_SITE_KEY: ${{ secrets.HOSTING_RE_CAPTCHA_SITE_KEY }}
          HOSTING_ANALYTICS_ID: ${{ secrets.HOSTING_ANALYTICS_ID }}
        run: |
          sed -i 's/HOSTING_RE_CAPTCHA_SITE_KEY/'$HOSTING_RE_CAPTCHA_SITE_KEY'/' config.toml
          sed -i 's/HOSTING_ANALYTICS_ID/'$HOSTING_ANALYTICS_ID'/' config.toml
          hugo --minify

      - name: deploy
        env:
          HOSTING_FTP_HOST: ${{ secrets.HOSTING_FTP_HOST }}
          HOSTING_FTP_USERNAME: ${{ secrets.HOSTING_FTP_USERNAME }}
          HOSTING_FTP_PASSWORD: ${{ secrets.HOSTING_FTP_PASSWORD }}
        run: |
          sudo apt-get install -y ncftp
          ncftpput -R -v -u ${HOSTING_FTP_USERNAME} -p ${HOSTING_FTP_PASSWORD} ${HOSTING_FTP_HOST} www/ public/*
